Correct the problems with Travis CI & the dockersetup
fosterfarrell9/mampf pull request #65
Opened 2020-08-24 19:08 UTC by christian-heusel

2020-08-25 17:11 UTC, fosterfarrell9 requested changes

2020-08-25 17:11 UTC, fosterfarrell9 commented on docker/run_tests/run_tests.sh
> +  bundle exec rails db:migrate > /usr/src/app/log/initialisation.log
There should be a `rails db:create` before, otherwise the migrations will fail (and they do fail, at least in my attempt to build the container).

2020-08-26 08:27 UTC, fosterfarrell9 approved these changes
Looks good now. By the way, if you want the tests to run through (and well, have half of them fail), the following files should be deleted because they "test" stuff that does no longer exist and therefore block the whole process:

- spec/controllers/api/v1/media_controller_spec.rb
- spec/controllers/api/v1/tags_controller_spec.rb
- /spec/models/vote_spec.rb

(That maybe more related to #66 and would be the first step there, but it also makes the tests look more realistic :-) )

2020-08-27 00:10 UTC, christian-heusel commented
Feel free to merge the PR then, I wont touch the tests :blush:

2020-08-27 08:26 UTC, merged